# Accents
PRODUCT_PACKAGES += \
    Ascendant \
    AnnieBrown \
    AnotherMessengerBlue \
    BenefitsPink \
    BlueGrey \
    Brown \
    CadPurple \
    CosmopolitanPink \
    Cyan \
    DarkBlue \
    DescendantBlue \
    EmyPurple \
    FerrariRed \
    FluoGreen \
    Indigo \
    Lime \
    McYellow \
    MessengerBlue \
    Mint \
    OrangeIsTheNewBlack \
    PaleGreen \
    RubyRed \
    Silver \
    SnapYellow \
    TGBlue \
    Teal \
    Tiffany \
    XDOrange \
    Yellow
