# Accents
PRODUCT_PACKAGES += \
    AnnieBrown \
    BenefitsPink \
    BlueGrey \
    Brown \
    CadPurple \
    CosmopolitanPink \
    Cyan \
    EmyPurple \
    FerrariRed \
    Indigo \
    Lime \
    McYellow \
    MessengerBlue \
    Mint \
    OrangeIsTheNewBlack \
    PSBlue \
    RazerGreen \
    RubyRed \
    Silver \
    SnapYellow \
    TGBlue \
    Teal \
    Tiffany \
    UserFive \
    UserFour \
    UserOne \
    UserSeven \
    UserSix \
    UserThree \
    UserTwo \
    WAGreen \
    XDAOrange \
    Yellow
